---
- name: Ensure APT cache is up to date
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true

- name: Install common packages
  apt:
    name: "{{ common_packages }}"
    state: latest
  become: true

- name: Uninstall unwanted packages
  apt:
    name: "{{ remove_packages }}"
    state: absent
  become: true

- import_tasks: spacemacs.yml
- import_tasks: zsh.yml
- import_tasks: chrome.yml


- name: Copy /etc/crda for iw to work
  copy:
    src: crda
    dest: /etc/crda
  become: true


- name: Install aws cli
  raw: pip install awscli


- name: Ensure ~/bin directory exists
  file:
    path: ~/bin
    state: directory
    mode: "u=rwx"

- name: Ensure ~/software directory exists
  file:
    path: ~/software
    state: directory
    mode: "u=rwx"

- name: Set remote url to allow pushing to this repo via ssh
  raw: git remote set-url origin git@github.com:xfthhxk/ansible-personal.git

- name: Copy .gitconfig if needed
  copy:
    src: .gitconfig
    dest: ~/
    force: false

- name: Copy .gitignore_global
  copy:
    src: .gitignore_global
    dest: ~/

- name: Install Slack
  shell: snap install slack --classic
  become: true

- name: Install Signal
  shell: snap install signal-desktop
  become: true
