---
- name: Ensure APT cache is up to date
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true
  become_user: root

- name: Install common packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ common_packages }}"
  become: true
  become_user: root

- include: spacemacs.yml

- name: Make zsh the login shell
  raw: chsh -s /usr/bin/zsh amehta
  become: true
  become_user: root

# ignore errors because everything works but the script tries to set the login shell to zsh
- name: Install oh-my-zsh
  raw: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  ignore_errors: true
