---
- name: Add additional ppas
  apt_repository:
    repo: "{{ item }}"
  with_items: "{{ utils_ppas }}"
  become: true

- name: Ensure APT cache is up to date
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true

- name: Install common packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ common_packages }}"
  become: true

- name: Uninstall unwanted packages
  apt:
    name: "{{ item }}"
    state: absent
  with_items: "{{ remove_packages }}"
  become: true

- include: spacemacs.yml
- include: zsh.yml
- include: chrome.yml
- include: flyway.yml


- name: Copy /etc/crda for iw to work
  copy:
    src: crda
    dest: /etc/crda
  become: true


- name: Install aws cli
  raw: pip install awscli


- name: Ensure ~/bin directory exists
  file:
    path: ~/bin
    state: directory
    mode: "u=rwx"

- name: Set remote url to allow pushing to this repo via ssh
  raw: git remote set-url origin git@github.com:xfthhxk/ansible-personal.git

- name: Copy .gitconfig if needed
  copy:
    src: .gitconfig
    dest: ~/
    force: false

- name: Copy .gitignore_global
  copy:
    src: .gitignore_global
    dest: ~/
