---
- name: Ensure APT cache is up to date
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true
  become_user: root

- name: Install common packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ common_packages }}"
  become: true
  become_user: root

- include: spacemacs.yml
- include: zsh.yml

- name: Set remote url to allow pushing to this repo via ssh
  raw: git remote set-url origin git@github.com:xfthhxk/ansible-personal.git
