---
- name: Ensure lein is available
  get_url:
    url: https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
    dest: ~/bin/lein
    mode: "u=rx"
  tags:
    - clojure
    - lein

- name: Install Clojure CLI
  raw: bash -c "$(curl -fsSL https://download.clojure.org/install/linux-install-{{ clojure_cli_version }}.sh)"
  become: true
  tags:
    - clojure
    - tools
