---
- name: Install docker
  shell: snap install docker
  become: true
  tags:
    - docker

- name: Install Docker Compose
  raw: curl -L https://github.com/docker/compose/releases/download/1.28.4/docker-compose-`uname -s`-x86_64 -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose
  become: true
  tags:
    - docker

- name: Setup docker group
  group:
    name: docker
    system: yes
    state: present
  become: true
  tags:
    - docker

- name: Add current user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
  become: true
  tags:
    - docker
