---
- name: Setup Docker GPG key
  apt_key:
    url:  https://yum.dockerproject.org/gpg
    state: present
  become: true

- name: Setup Docker apt repository
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo/ ubuntu-{{ ansible_lsb.codename }} main
  become: true

- name: Ensure APT cache is up to date
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true

- name: Install Docker related packages
  apt: name={{item}} state=latest
  with_items:
    - linux-image-extra-{{ ansible_kernel }}
    - linux-image-extra-virtual
    - docker-engine
    - docker-compose
    - virtualbox
  become: true


- name: Setup docker group
  group:
    name: docker
    system: yes
    state: present
  become: true

- name: Add current user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
  become: true

#- name: Install Docker Machine
#  raw: docker-machine --version || curl -L https://github.com/docker/machine/releases/download/v0.11.0/docker-machine-`uname -s`-`uname -m` >/tmp/docker-machine && chmod +x /tmp/docker-machine && cp /tmp/docker-machine /usr/local/bin/docker-machine
#  become: true
