---
- name: Setup Docker GPG key
  apt_key:
    url:   https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true

# repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
- name: Setup Docker apt repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
  become: true

- name: Ensure APT cache is up to date
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true

- name: Install Docker related packages
  apt:
    name:
      - docker-ce
    state: latest
  become: true

- name: Install Docker Compose
  raw: curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname -s`-x86_64 -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose
  become: true
  tags:
    - docker


- name: Setup docker group
  group:
    name: docker
    system: yes
    state: present
  become: true

- name: Add current user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
  become: true
