---
- name: Install GCP SDK
  shell: snap install google-cloud-sdk --classic
  become: true
  tags:
    - gcp


# - name: Install firebase tools
#   npm:
#    name: firebase-tools
#    global: yes
#   become: true
#   tags:
#     - gcp
