---
- name: Ensure APT cache is up to date
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true

- name: Install Open JDK 11
  become: true
  apt:
    name: openjdk-11-jdk
    state: latest
  tags:
    - jdk11
